---

- name: Terraform deployment with Ansible
  hosts: localhost
  connection: local
  tasks:
    - name: Provisioning infrastructure with Terraform
      cloud.terraform.terraform:
        project_path: "{{ playbook_dir }}"
        force_init: true
        state: present
