---
- name: Provision infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create container for Community Call demo
      community.docker.docker_container:
        name: community-call-demo
        image: timgrt/rockylinux9-ansible
        state: started
        command: "/usr/lib/systemd/systemd"
        cgroupns_mode: host
        hostname: rocky9
        tmpfs:
          - /run
          - /tmp
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
          - /var/lib/containerd
        privileged: true
    - name: Copy sshd_config to /tmp
      ansible.builtin.template:
        src: sshd-config-default.j2
        dest: /tmp/sshd-config-insecure
        mode: "0644"
    - name: Add insecure parameters
      ansible.builtin.lineinfile:
        path: /tmp/sshd-config-insecure
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
      loop:
        - line: PermitRootLogin yes
          regexp: ^#PermitRootLogin
        - line: PasswordAuthentication yes
          regexp: ^#PasswordAuthentication
        - line: PermitEmptyPasswords yes
          regexp: ^PermitEmptyPasswords
        - line: MaxAuthTries 5000
          regexp: ^#MaxAuthTries

- name: Configure infrastructure
  hosts: demo
  tasks:
    - name: Update yum cache for faster package installation  # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: yum makecache
      changed_when: false
    - name: Install packages used in demo
      ansible.builtin.yum:
        name: openssh-server
        state: present
